[options]
admin_passwd = $pbkdf2-sha512$600000$JcQ4x3jvXYuR0jpnrDWGMA$Eiqt.Hz2E/ihaU0ys1oO5G7v7ea5P5sy9JxRTo1jERNtKKnyG8.usqR1ZuzYH0Bz85GHR9/t9UcaKhZg0CXVQg
db_host = db
db_user = odoo
db_password = odoo
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
log_level = info

